services:
  # MongoDB
  database:
    container_name: truba_mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - db-network
    restart: unless-stopped

  # Backend
  backend:
    container_name: truba_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URI=mongodb://database:27017/truba_db
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - db-network
      - http-network
    restart: unless-stopped

  # Frontend
  frontend:
    container_name: truba_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - http-network
    restart: unless-stopped

  # Volumes
volumes:
  mongo_data:

  # Networks
networks:
  db-network:
    driver: bridge
  http-network:
    driver: bridge
