services:
  # Backend
  backend:
    container_name: truba_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    networks:
      - http-network
    restart: unless-stopped

  # Frontend
  frontend:
    container_name: truba_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    networks:
      - http-network
    restart: unless-stopped
  # Networks
networks:
  http-network:
    driver: bridge
